### ISSUE TITLE
Mex compilation error: ‘KAZE’ was not declared in this scope

### ISSUE THREAD

**Issue by siddharthsrivastava** [pablofdezalc/kaze#5]
Hi

I am trying to interface KAZE with matlab. But while compilation, I get the following error:
>kaze.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
>kaze.cpp:198:3: error: ‘KAZE’ was not declared in this scope
>   KAZE evolution(options);
>kaze.cpp:198:3: note: suggested alternatives:
>In file included from /usr/local/include/opencv2/opencv.hpp:50:0,
>                 from ../src/lib/utils.h:12,
>                 from ../src/lib/KAZE.h:15,
>                 from kaze.cpp:22:
>/usr/local/include/opencv2/features2d.hpp:514:20: note:   ‘cv::KAZE’
> class CV_EXPORTS_W KAZE : public Feature2D
                    ^
>In file included from kaze.cpp:22:0:
>../src/lib/KAZE.h:43:9: note:   ‘libKAZE::KAZE’
>   class KAZE {
       
> kaze.cpp:199:3: error: ‘evolution’ was not declared in this scope
>  evolution.Create_Nonlinear_Scale_Space(img_32);
   

    mex: compile of ' "kaze.cpp"' failed.

**Comment by pablofdezalc** [comment]
Hi,

I have updated kaze.cpp. I made some minor changes to match latest OpenCV and KAZE version. Now, the compilation should work fine. 

Regards
